import { mkdirSync, writeFileSync } from 'node:fs';
import type { Level } from '../src/puzzle';

/** Keep authored data in modest files and matching production chunks. */
export function writeLevelCatalog(catalog: Level[]): void {
  mkdirSync('src/levels', { recursive: true });
  const imports: string[] = [], names: string[] = [];
  for (let offset = 0; offset < catalog.length; offset += 100) {
    const first = String(offset + 1).padStart(3, '0');
    const last = String(Math.min(offset + 100, catalog.length)).padStart(3, '0');
    const name = `LEVELS_${first}_${last}`;
    const filename = `levels-${first}-${last}`;
    const data = catalog.slice(offset, offset + 100);
    writeFileSync(`src/levels/${filename}.ts`,
      `/** Verified campaign levels ${first}–${last}. Generated by build:levels. */\nimport type { Level } from '../puzzle';\nexport const ${name}: Level[] = ${JSON.stringify(data)};\n`);
    imports.push(`import { ${name} } from './levels/${filename}';`);
    names.push(`...${name}`);
  }
  writeFileSync('src/level-catalog.ts',
    `/** Verified offline catalogue v3; campaign seeds remain stable. */\nimport type { Level } from './puzzle';\n${imports.join('\n')}\nexport const LEVEL_CATALOG: Level[] = [${names.join(', ')}];\n`);
}
